version: 0.2
phases:
  install:
    commands:
      - echo Installing dependencies...
      - composer install
  build:
    commands:
      - echo Build started on `date`
      - echo Building the project...
artifacts:
  files:
    - '**/*'